Repository bustle/ember-mobiledoc-editor, pull requests merged in 2020-06, with the labels that each got.

#180 Adopt release-it for automating releases and changelog management
  README.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#182 Remove custom hash helper in favor of version ember's built-in one
  addon/helpers/hash.js
  app/helpers/hash.js
  config/ember-try.js
  tests/unit/helpers/hash-test.js
Labels: breaking, bug

#163 Move away from deprecated sendAction function
  addon/components/mobiledoc-editor/component.js
Labels: enhancement
